#!/bin/bash --login
#SBATCH -N 2
#SBATCH -n 12
#SBATCH --time=0:20:00
#SBATCH --job-name="task_7"
#SBATCH --mem-per-cpu=1024
#SBATCH --output=stdout.txt
#SBATCH --error=stderr.txt

module load intel/2022.1.2
module load quantum_espresso/7.1
#======START=====

srun -n 12   pw.x -npools 2 < scf.in  > scf.out
srun -n 12   pw.x -npools 2 < bands.in >  bands.out
