#!/bin/bash --login
#SBATCH -N 1
#SBATCH -n 2
#SBATCH --time=0:10:00
#SBATCH --job-name="task_0c"
#SBATCH --mem-per-cpu=1024
#SBATCH --output=stdout.txt
#SBATCH --error=stderr.txt

module load intel/2022.1.2
module load quantum_espresso/7.1
#======START=====

a=5.43
alat=`echo "${a} / 0.529177" | bc -l`

cat >pw.in << EOF
 &control
    verbosity='high'
    calculation='scf'
    restart_mode='from_scratch'
    prefix='SI'
    pseudo_dir = './',
    outdir='./'
 /
 &system
    ibrav=1
    celldm(1)=${alat}
    nat=8,
    ntyp=1,
    ecutwfc = 30,
    occupations='smearing',
    degauss=0.001
 /
 &electrons
    conv_thr = 1.0e-8
    mixing_beta = 0.5
 /
 &ions
 /
ATOMIC_SPECIES
  Si  28.086  Si.pbe-mt_fhi.UPF
ATOMIC_POSITIONS  crystal
Si     0.000000    0.000000    0.000000
Si     0.000000    0.500000    0.500000
Si     0.500000    0.000000    0.500000
Si     0.500000    0.500000    0.000000
Si     0.750000    0.250000    0.750000
Si     0.250000    0.250000    0.250000
Si     0.250000    0.750000    0.750000
Si     0.750000    0.750000    0.250000
K_POINTS automatic
2 2 2 1 1 1
EOF
srun -n 2 -d 1  pw.x <pw.in > si.out
