#!/bin/bash 
#SBATCH -N 1
#SBATCH -n 2
#SBATCH --time=0:10:00
#SBATCH --job-name="SiC_bands"
#SBATCH --mem-per-cpu=1024
#SBATCH --output=stdout.txt
#SBATCH --error=stderr.txt

module load intel/2022.1.2
module load quantum_espresso/7.1
#======START=====

srun -n 2  pw.x <scf.in > scf.out
srun -n 2  pw.x <bands.in > bands.out

