#!/bin/bash 
#SBATCH -N 1
#SBATCH -n 4
#SBATCH --time=0:10:00
#SBATCH --job-name="Si"
#SBATCH --mem-per-cpu=1024
#SBATCH --output=stdout.txt
#SBATCH --error=stderr.txt

module load intel/2022.1.2
module load quantum_espresso/7.1
#======START=====
srun -n 4 pw.x -npools 2 -in scf.in   > scf.out
srun -n 4 pw.x -npools 2 -in bands.in > bands.out
srun -n 4 bands.x -npools 2 -in bands_post_proc.in > bands_post_proc.out
